name: Build Test on different OSs

on:
  push:
    branches:
    - '**' # Every branch
    - '!gh-pages' # Excluding website

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.6.1'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'

    - name: Generate sources
      run: |
        mkdir build
        cmake -B ./build -S .
      shell: bash

    - name: Build project
      run: |
        cd build
        cmake --build .
      shell: bash

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.6.1
        aqtversion: '==3.1.*'
        host: 'linux'
        target: 'desktop'
        install-deps: 'true'
        arch: 'gcc_64'

    - name: Generate sources
      run: |
        mkdir build
        cmake -B ./build -S .
      shell: bash

    - name: Build project
      run: |
        cd build
        cmake --build .
      shell: bash

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.6.1
        aqtversion: '==3.1.*'
        host: 'windows'
        target: 'desktop'
        install-deps: 'true'
        arch: 'win64_mingw'

    - name: Generate sources
      run: |
        mkdir build
        cmake -G "MinGW Makefiles" -B ./build -S .
      shell: pwsh

    - name: Build project
      run: |
        cd build
        cmake --build .
      shell: pwsh
