name: Build Test on different OSs

on: 
  push:
    branches:
      - master

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.6.1'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'

    - name: Verify Qt Installation
      run: |
        qmake --version
      shell: bash

    - name: Build the project
      run: |
        qmake mgfield.pro
        make
      shell: bash

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.6.1
        aqtversion: '==3.1.*'
        host: 'linux'
        target: 'desktop'
        install-deps: 'true'
        arch: 'gcc_64'

    - name: Verify Qt Installation
      run: |
        qmake6 --version
      shell: bash

    - name: Build the project
      run: |
        qmake6 mgfield.pro
        make
      shell: bash

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.6.1
        aqtversion: '==3.1.*'
        host: 'windows'
        target: 'desktop'
        install-deps: 'true'
        arch: 'win64_mingw'

    - name: Verify Qt Installation
      run: |
        qmake --version
      shell: pwsh

    - name: Build the project
      run: |
        qmake mgfield.pro
        make
      shell: pwsh
