name: Test on macOS Ubuntu and Windows

on:
  push:
    branches: [ github-actions-test ]
  pull_request:
    branches: [ github-actions-test ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      run: |
        if ! command -v qmake &> /dev/null; then
          echo "Qt is not installed. Installing..."
          brew install qt
          echo "QT_PATH=$(brew --prefix qt)" >> $GITHUB_ENV
          echo "export PATH=$QT_PATH/bin:$PATH" >> $GITHUB_ENV
        else
          echo "Qt is already installed."
        fi
      shell: bash

    - name: Verify Qt Installation
      run: |
        qmake --version
      shell: bash

    - name: Build the project
      run: |
        qmake mgfield.pro
        make
      shell: bash
      env:
        QT_PATH: ${{ env.QT_PATH }}

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt install qt6-base-dev
        sudo apt install qtcreator
      shell: bash

    - name: Verify Qt Installation
      run: |
        qmake6 --version
      shell: bash

    - name: Build the project
      run: |
        qmake6 mgfield.pro
        make
      shell: bash

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      run: |
        choco install qt5-default
      shell: pwsh

    - name: Verify Qt Installation
      run: |
        qmake --version
      shell: pwsh

    - name: Build the project
      run: |
        qmake mgfield.pro
        make
      shell: pwsh
