name: Windows build workflow

on:
  push:
    branches:
    - '**'        # Every branch
    - '!gh-pages' # Excluding website

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.6.1
        aqtversion: '==3.1.*'
        host: 'windows'
        target: 'desktop'
        install-deps: 'true'
        arch: 'win64_mingw'

    - name: Generate sources
      run: |
        mkdir build
        cmake -G "MinGW Makefiles" -B ./build -S .
      shell: pwsh

    - name: Build project
      run: |
        cd build
        cmake --build .
      shell: pwsh
